import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'English' | 'Hindi' | 'Spanish' | 'French' | 'German' | 'Japanese' | 'Chinese';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  English: {
    dashboard: 'Dashboard',
    settings: 'Settings',
    journal: 'Journal',
    habits: 'Habits',
    reminders: 'Reminders',
    ai_coach: 'AI Coach',
    profile: 'Profile',
    logout: 'Logout',
    back_to_dashboard: 'Back to Dashboard',
    save: 'Save',
    saved: 'Saved',
    delete: 'Delete',
    notifications: 'Notifications',
    privacy: 'Privacy & Security',
    appearance: 'Appearance',
    language: 'Language',
    daily_reminders: 'Daily Reminders',
    weekly_reports: 'Weekly Growth Reports',
    ai_insights: 'AI Insight Alerts',
    email_alerts: 'Email Notifications',
    theme: 'Theme',
    font_size: 'Font Size',
    reduced_motion: 'Reduced Motion',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    settings_updated: 'Settings updated successfully',
    welcome_back: 'Welcome back',
    how_feeling: 'How are you feeling today?',
    start_typing: 'Start typing your thoughts...',
    growth_trends: 'Growth Trends',
    no_data_yet: 'No data yet. Start journaling to see your trends!',
  },
  Hindi: {
    dashboard: 'डैशबोर्ड',
    settings: 'सेटिंग्स',
    journal: 'जर्नल',
    habits: 'आदतें',
    reminders: 'अनुस्मारक',
    ai_coach: 'एआई कोच',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    back_to_dashboard: 'डैशबोर्ड पर वापस जाएं',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    delete: 'हटाएं',
    notifications: 'सूचनाएं',
    privacy: 'गोपनीयता और सुरक्षा',
    appearance: 'दिखावट',
    language: 'भाषा',
    daily_reminders: 'दैनिक अनुस्मारक',
    weekly_reports: 'साप्ताहिक विकास रिपोर्ट',
    ai_insights: 'एआई अंतर्दृष्टि अलर्ट',
    email_alerts: 'ईमेल सूचनाएं',
    theme: 'थीम',
    font_size: 'फ़ॉन्ट आकार',
    reduced_motion: 'कम गति',
    light: 'हल्का',
    dark: 'गहरा',
    system: 'सिस्टम',
    small: 'छोटा',
    medium: 'मध्यम',
    large: 'बड़ा',
    settings_updated: 'सेटिंग्स सफलतापूर्वक अपडेट की गईं',
    welcome_back: 'वापसी पर स्वागत है',
    how_feeling: 'आज आप कैसा महसूस कर रहे हैं?',
    start_typing: 'अपने विचार लिखना शुरू करें...',
    growth_trends: 'विकास के रुझान',
    no_data_yet: 'अभी तक कोई डेटा नहीं है। अपने रुझान देखने के लिए जर्नलिंग शुरू करें!',
  },
  Spanish: {
    dashboard: 'Tablero',
    settings: 'Ajustes',
    journal: 'Diario',
    habits: 'Hábitos',
    reminders: 'Recordatorios',
    ai_coach: 'Entrenador AI',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    back_to_dashboard: 'Volver al tablero',
    save: 'Guardar',
    saved: 'Guardado',
    delete: 'Eliminar',
    notifications: 'Notificaciones',
    privacy: 'Privacidad y Seguridad',
    appearance: 'Apariencia',
    language: 'Idioma',
    daily_reminders: 'Recordatorios diarios',
    weekly_reports: 'Informes semanales',
    ai_insights: 'Alertas de IA',
    email_alerts: 'Notificaciones por correo',
    theme: 'Tema',
    font_size: 'Tamaño de fuente',
    reduced_motion: 'Movimiento reducido',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    small: 'Pequeño',
    medium: 'Mediano',
    large: 'Grande',
    settings_updated: 'Ajustes actualizados correctamente',
    welcome_back: 'Bienvenido de nuevo',
    how_feeling: '¿Cómo te sientes hoy?',
    start_typing: 'Empieza a escribir tus pensamientos...',
    growth_trends: 'Tendencias de crecimiento',
    no_data_yet: 'Aún no hay datos. ¡Empieza a escribir para ver tus tendencias!',
  },
  French: {
    dashboard: 'Tableau de bord',
    settings: 'Paramètres',
    journal: 'Journal',
    habits: 'Habitudes',
    reminders: 'Rappels',
    ai_coach: 'Coach IA',
    profile: 'Profil',
    logout: 'Déconnexion',
    back_to_dashboard: 'Retour au tableau de bord',
    save: 'Enregistrer',
    saved: 'Enregistré',
    delete: 'Supprimer',
    notifications: 'Notifications',
    privacy: 'Confidentialité et Sécurité',
    appearance: 'Apparence',
    language: 'Langue',
    daily_reminders: 'Rappels quotidiens',
    weekly_reports: 'Rapports hebdomadaires',
    ai_insights: 'Alertes IA',
    email_alerts: 'Notifications par e-mail',
    theme: 'Thème',
    font_size: 'Taille de police',
    reduced_motion: 'Mouvement réduit',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    small: 'Petit',
    medium: 'Moyen',
    large: 'Grand',
    settings_updated: 'Paramètres mis à jour avec succès',
    welcome_back: 'Bon retour',
    how_feeling: 'Comment vous sentez-vous aujourd\'hui ?',
    start_typing: 'Commencez à écrire vos pensées...',
    growth_trends: 'Tendances de croissance',
    no_data_yet: 'Pas encore de données. Commencez votre journal pour voir vos tendances !',
  },
  German: {
    dashboard: 'Dashboard',
    settings: 'Einstellungen',
    journal: 'Journal',
    habits: 'Gewohnheiten',
    reminders: 'Erinnerungen',
    ai_coach: 'KI-Coach',
    profile: 'Profil',
    logout: 'Abmelden',
    back_to_dashboard: 'Zurück zum Dashboard',
    save: 'Speichern',
    saved: 'Gespeichert',
    delete: 'Löschen',
    notifications: 'Benachrichtigungen',
    privacy: 'Datenschutz & Sicherheit',
    appearance: 'Erscheinungsbild',
    language: 'Sprache',
    daily_reminders: 'Tägliche Erinnerungen',
    weekly_reports: 'Wöchentliche Berichte',
    ai_insights: 'KI-Einblicke',
    email_alerts: 'E-Mail-Benachrichtigungen',
    theme: 'Design',
    font_size: 'Schriftgröße',
    reduced_motion: 'Reduzierte Bewegung',
    light: 'Hell',
    dark: 'Dunkel',
    system: 'System',
    small: 'Klein',
    medium: 'Mittel',
    large: 'Groß',
    settings_updated: 'Einstellungen erfolgreich aktualisiert',
    welcome_back: 'Willkommen zurück',
    how_feeling: 'Wie fühlst du dich heute?',
    start_typing: 'Fang an, deine Gedanken aufzuschreiben...',
    growth_trends: 'Wachstumstrends',
    no_data_yet: 'Noch keine Daten. Fang an zu schreiben, um deine Trends zu sehen!',
  },
  Japanese: {
    dashboard: 'ダッシュボード',
    settings: '設定',
    journal: 'ジャーナル',
    habits: '習慣',
    reminders: 'リマインダー',
    ai_coach: 'AIコーチ',
    profile: 'プロフィール',
    logout: 'ログアウト',
    back_to_dashboard: 'ダッシュボードに戻る',
    save: '保存',
    saved: '保存済み',
    delete: '削除',
    notifications: '通知',
    privacy: 'プライバシーとセキュリティ',
    appearance: '外観',
    language: '言語',
    daily_reminders: '毎日のリマインダー',
    weekly_reports: '週次レポート',
    ai_insights: 'AIインサイト',
    email_alerts: 'メール通知',
    theme: 'テーマ',
    font_size: 'フォントサイズ',
    reduced_motion: '視覚効果を減らす',
    light: 'ライト',
    dark: 'ダーク',
    system: 'システム',
    small: '小',
    medium: '中',
    large: '大',
    settings_updated: '設定が正常に更新されました',
    welcome_back: 'おかえりなさい',
    how_feeling: '今日の気分はどうですか？',
    start_typing: '考えを書き留めましょう...',
    growth_trends: '成長トレンド',
    no_data_yet: 'データがまだありません。ジャーナルを始めてトレンドを確認しましょう！',
  },
  Chinese: {
    dashboard: '仪表板',
    settings: '设置',
    journal: '日志',
    habits: '习惯',
    reminders: '提醒',
    ai_coach: 'AI教练',
    profile: '个人资料',
    logout: '登出',
    back_to_dashboard: '返回仪表板',
    save: '保存',
    saved: '已保存',
    delete: '删除',
    notifications: '通知',
    privacy: '隐私与安全',
    appearance: '外观',
    language: '语言',
    daily_reminders: '每日提醒',
    weekly_reports: '每周报告',
    ai_insights: 'AI洞察警报',
    email_alerts: '邮件通知',
    theme: '主题',
    font_size: '字体大小',
    reduced_motion: '减少动态效果',
    light: '浅色',
    dark: '深色',
    system: '系统',
    small: '小',
    medium: '中',
    large: '大',
    settings_updated: '设置更新成功',
    welcome_back: '欢迎回来',
    how_feeling: '你今天感觉如何？',
    start_typing: '开始记录你的想法...',
    growth_trends: '成长趋势',
    no_data_yet: '暂无数据。开始记录日志以查看你的趋势！',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'English';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
